# Copyright 2026 Jalapeno Labs

services:
  transcriber:
    container_name: seraphim-transcriber
    build:
      context: services/transcriber
    restart: unless-stopped
    ports:
      - "9901:2700"
    healthcheck:
      test: ["CMD", "bash", "-c", "exec 3<>/dev/tcp/127.0.0.1/2700"]
      interval: 3s
      timeout: 10s
      retries: 6
      start_period: 1s
    networks:
      - main

  database:
    container_name: seraphim-database
    image: postgres:17.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 2s
      timeout: 5s
      retries: 6
      start_period: 1s
    ports:
      - "9902:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - main

  prisma-studio:
    container_name: seraphim-prisma-studio
    build:
      context: .
      dockerfile: services/prisma_studio/Dockerfile
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?schema=public"
    healthcheck:
      test: ["CMD", "bash", "-c", "exec 3<>/dev/tcp/127.0.0.1/5555"]
      interval: 2s
      timeout: 5s
      retries: 6
      start_period: 2s
    ports:
      - "5555:5555"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - main

networks:
  main:

volumes:
  database_data:
